### ISSUE TITLE
add QA stack + initial test env

### ISSUE THREAD

**Issue by ro0NL** [ro0NL/symfony-docker#6]
- php-cs-fixer / psalm / phpunit
- run full smoke test by default using `ENTRYPOINT / CMD`

assume an in-memory db:

```yaml
# app/config/config_test.yml

doctrine:
    dbal:
        driver:  pdo_sqlite
        memory:  true
        charset: UTF8
```
